### ISSUE TITLE
Implementation can't be downloaded

### ISSUE THREAD

**Issue by sundaym** [oberon-lang/oberon-lang.github.io#1]
"Mixed Content: The site at 'https://github.com/' was loaded over a secure connection, but the file at 'http://software.rochus-keller.ch/OberonIDE_win64.zip' was loaded over an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details."

I need to open F12 and click link.

**Comment by rochus-keller** [comment]
So you finally could download the file or not?

**Comment by sundaym** [comment]
> So you finally could download the file or not?

Thanks for your reply.
I finally downloaded the file.

**Comment by rochus-keller** [comment]
I don't use Chrome, but on the most recent versions of Edge or Firefox I just get a warning, but can explicitly allow the download. Browsers should protect their users, but not patronize them. Did your Chrome browser offer you a way to get around the block, or did you have to switch to another brower?

**Comment by sundaym** [comment]
> I don't use Chrome, but on the most recent versions of Edge or Firefox I just get a warning, but can explicitly allow the download. Browsers should protect their users, but not patronize them. Did your Chrome browser offer you a way to get around the block, or did you have to switch to another brower?

Firefox is OK. Chrome needs to allow insecure content in Settings(Privacy and security).
Thank you sir, I will close this issue.
